### ISSUE TITLE
points problematic

### ISSUE THREAD

**Issue by janenie** [harvardnlp/boxscore-data#1]
Hi, 
While I read the data, I found that the first sentence describing the winner of this game, the winner & loser are mistaken. I am not sure if I understand the data correctly. Below is a example. 
 
[Summary]: The Memphis Grizzlies ( 31 - 12 ) beat the Philadelphia 76ers ( 8 - 36 ) , 101 - 83 .
[Home_line]: "TEAM-CITY": "Philadelphia", "TEAM-PTS": "101","TEAM-NAME": "76ers"
[vis_line]: "TEAM-CITY": "Memphis", "TEAM-PTS": "83","TEAM-AST": "18", "TEAM-NAME": "Grizzlies"

**Comment by swiseman** [comment]
Hi,

Yes, it looks like in this example the team statistics got attached to the wrong names. Aligning the various statistics and the text is a somewhat noisy process, and there are likely to be a few errors here and there. My impression from spot-checking when I created the data is that this is relatively rare, though it may make sense to keep a list of errors like this so we can further clean up the data.

**Comment by janenie** [comment]
Hi,
I think the dataset is problematic, I check first 10 data on the dev set, 5 of the answers (first sentence) are wrong according to the data structure.

Would you mind exam it carefully ? Or I understand the data incorrectly

Thanks

**Comment by swiseman** [comment]
Sure, let me take a look and I'll get back to you. (I'm out of the office today but I can try to get to it tomorrow or the next day...)

**Comment by janenie** [comment]
Any updates in checking the data ?

**Comment by swiseman** [comment]
Yes, thanks for bringing this issue to my attention. After some investigation it looks like what happened is that on a subset of the data the order of home/away team names returned by the nba_py API changed. As a result, for some games the team names were attached to the wrong rows in the line-score (that is, they were flipped). I've just pushed an updated dataset where the names have been unflipped.

Just to be clear about what exactly was and wasn't wrong in the original data: all the boxscore data was correct, and all the line-score data was internally consistent, except that in some cases the team name and city were attached to the wrong row in the line-score.

I will also be updating results to reflect this change in the data.
