### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by RunxinXu** [harvardnlp/boxscore-data#2]
Hello！Recently I have read "Challenges in Data-to-Document Generation" and it was really cool!  However, I wonder if I can know how to caluculate the Relation Generation (RG). Maybe scripts or something? Because I do not know how you calculate precision of unique relations extracted from generated text that also appear in s, with different pair types (r.t)? Thanks!

**Comment by swiseman** [comment]
The original implementation is in this [repo](https://github.com/harvardnlp/data2text); you can find a much improved implementation [here](https://github.com/ratishsp/data2text-plan-py).
